### PR TITLE
refactor(event-watcher): parallize _checkEvents

### PR DESCRIPTION
**Pull request by mvayngrib**
the diff looks messy, but essentially i just extracted the `for` loop in `_checkEvents` to `_checkEvent` to be able to parallelize across events. And also parallelized the dupe event check.

note: your test-contract-interactions test has a race condition as it might receive 1 or 2 blocks, depending on subscription timing

### CODE REVIEW

**Comment by kfichter** [comment]
Heyo! Thanks for the contribution :-) just looked through it, LGTM. Gonna go ahead and fix the conflict and merge.

**Comment by kfichter** [comment]
> note: your test-contract-interactions test has a race condition as it might receive 1 or 2 blocks, depending on subscription timing

Good point. We need to do a better job in those tests... I'll go ahead and make an issue for it.

**Comment by kfichter** [comment]
Merged. Awesome job on this, don't know why I didn't think to parallelize sooner.

**Comment by mvayngrib** [comment]
cool, thanks :)

**Pull request merged**
