### PR TITLE
moved plasma-utils dependency to github version

### PR DESCRIPTION
**Pull request by kartsims**
I had some trouble getting `npm install` to work on this repo, because of the `file://../plasma-utils` dependency (running Node v10.14.2 as er the README)

In general it seems to be a better practice to rely on direct github source code imho so I am proposing a switch in `package.json`. Another improvement (pending direct npm dependency which [seems to be the plan ultimately](plasma-group/plasma-utils#15)) would be to refer to a specific stable branch of `plasma-utils`

### CODE REVIEW

**Comment by kfichter** [comment]
Good call, thank you! 

Was definitely the plan to move to a `npm` module but was just going with local while we were developing. Probably stable enough at this point that we can point at github. :+1:

**Comment by kartsims** [comment]
happy to help! thanks to you and the team for all the good work already accomplished !

I am reading through the code for now, and will try to take a stab at the "good first issue"s

Also, would you be interested in publishing the docs of this repo to github pages ? I could help on that but don't want to open an issue on that if you believe it to be relevant, or if you plan on doing a more general documentation resource.

**Comment by kfichter** [comment]
@kartsims Sorry for the late response! We're currently hosting documentation at Read the Docs: https://plasma-core.readthedocs.io/en/latest/. I'm going to update the README with a link to the docs in a second. I'll also be opening issues today with requests for help with docs, most of those will be `good first issue`s!

**Comment by kartsims** [comment]
awesome, thanks for your answer

**Pull request merged**
