### PR TITLE
DBService added to support multiple databases for multiple plasma chains

### PR DESCRIPTION
**Pull request by Luiserebii**
Hello, 

I managed to write in a new class called DBService to handle unique databases per chain. It inherits functionality from the base-service.js file, and allows for the following syntax to be used to open and manipulate opened databases:

```
this.services.db.openDB([database_name])   //loads database into the db object
this.services.db.[database_name].set()   //database is easily accessible by name!
```

I have also written a few tests for it within test-db-service.js. They should check that:
- DBService can load one or more existing databases 
- All database functionality is callable by referencing a loaded database within DBService
- Mutliple databases can hold unique values with the same key, without one affecting the other

It is currently written under EphemDB, but can be changed as needed for whichever implementation extending the BaseDBProvider. The only current minor issue is that the tests, while passing, some seem to appear "out of order" (the last two "describe" tests (Database/Multiple Databases) appear at the very top when running `npm test`, without their "titles"). 

I hope I made everything as legible as possible; juggling two different databases and values within the DBService test file made it a little difficult to write in the most readable way, so I made sure to add comments where I could to break them up.

This pull request is referencing: https://github.com/plasma-group/plasma-core/issues/59

Thank you!
Luiserebii~

### CODE REVIEW

**Comment by kfichter** [comment]
Heyo I think that .swp file should be removed before we merge.

**Comment by kfichter** [comment]
Otherwise LGTM!

**Comment by Luiserebii** [comment]
@kfichter Whoops, my mistake! Should I make another PR to remove it?

**Comment by kfichter** [comment]
No worries, I've gone ahead and deleted it in a recent commit :-)

**Comment by Luiserebii** [comment]
Great to hear, thanks! I'll make sure to look out for .swp files next time.

**Pull request merged**
